services:
  app:
    build:
      context: ./backend
    restart: always
    ports:
      - 9999:8000
    command: [ "docker/app.sh" ]
    volumes:
      - ./backend/logs/log_backup:/logs/log_backup
    depends_on:
      - pg
    env_file:
      - ./backend/.env

  pg:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.2.0
    container_name: redis
    restart: always
    #    command: --port 6379
    #    expose:
    #      - 6379
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - pg

  celery:
    build:
      context: ./backend
    command: [ "docker/celery.sh", "celery" ]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
    env_file:
      - ./backend/.env

  flower:
    build:
      context: ./backend
    restart: always
    command: [ "docker/celery.sh", "flower" ]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
    ports:
      - 8888:5555
    depends_on:
      - celery
    env_file:
      - ./backend/.env

volumes:
  app:
  postgres_data: